// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brtpixpzaequyohuvtin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJydHBpeHB6YWVxdXlvaHV2dGluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTIzNzYsImV4cCI6MjA2OTM2ODM3Nn0.25cQZb0-5Y4PnBIAbNc7vv5fMUwqpMQuAh2BQ1-NrSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});